### ISSUE TITLE
setup_img.sh: emerge traceback

### ISSUE THREAD

**Issue by telans** [toralf/tinderbox#1]
```
==> ./img1/17.1_systemd-20201125-003545/var/tmp/tb/setup.sh.log <==
+ set -e
+ export GCC_COLORS=
+ GCC_COLORS=
+ date
Tue Nov 24 11:35:59 -00 2020
+ echo '#setup rsync'
+ tee /var/tmp/tb/task
#setup rsync
+ rsync --archive --cvs-exclude /mnt/repos/gentoo /var/db/repos/
+ [[ n = \y ]]
+ [[ n = \y ]]
+ [[ n = \y ]]
+ date
Tue Nov 24 11:36:10 -00 2020
+ echo '#setup configure'
+ tee /var/tmp/tb/task
#setup configure
+ echo 17.1_systemd-20201125-003545
+ useradd -u 1000 tinderbox
+ [[ ! n = \y ]]
+ cat
++ date
+ locale-gen -j1
 * Generating 6 locales (this might take a while) with 1 jobs
 *  (1/6) Generating C.UTF-8 ...                                                                                                       [ ok ]
 *  (2/6) Generating de_DE.ISO-8859-1 ...                                                                                              [ ok ]
 *  (3/6) Generating de_DE.UTF-8.UTF-8@euro ...                                                                                        [ ok ]
 *  (4/6) Generating de_DE.ISO-8859-15@euro ...                                                                                        [ ok ]
 *  (5/6) Generating en_US.ISO-8859-1 ...                                                                                              [ ok ]
 *  (6/6) Generating en_US.UTF-8 ...                                                                                                   [ ok ]
 * Generation complete
 * Adding locales to archive ...                                                                                                       [ ok ]
+ eselect locale set en_US.UTF-8
Setting LANG to en_US.UTF-8 ...
Run ". /etc/profile" to update the variable in your shell.
+ env-update
>>> Regenerating /etc/ld.so.cache...
+ source /etc/profile
++ '[' -e /etc/profile.env ']'
++ . /etc/profile.env
+++ export CONFIG_PROTECT=/usr/share/gnupg/qualified.txt
+++ CONFIG_PROTECT=/usr/share/gnupg/qualified.txt
+++ export 'CONFIG_PROTECT_MASK=/etc/sandbox.d /etc/gentoo-release /etc/terminfo /etc/ca-certificates.conf'
+++ CONFIG_PROTECT_MASK='/etc/sandbox.d /etc/gentoo-release /etc/terminfo /etc/ca-certificates.conf'
+++ export GCC_SPECS=
+++ GCC_SPECS=
+++ export INFOPATH=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.34/info:/usr/share/info
+++ INFOPATH=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.34/info:/usr/share/info
+++ export LANG=en_US.UTF-8
+++ LANG=en_US.UTF-8
+++ export 'LESS=-R -M --shift 5'
+++ LESS='-R -M --shift 5'
+++ export 'LESSOPEN=|lesspipe %s'
+++ LESSOPEN='|lesspipe %s'
+++ export MANPAGER=manpager
+++ MANPAGER=manpager
+++ export MANPATH=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.34/man:/usr/local/share/man:/usr/share/man
+++ MANPATH=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/man:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.34/man:/usr/local/share/man:/usr/share/man
+++ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
+++ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
+++ export ROOTPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
+++ ROOTPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
++ export EDITOR=/bin/nano
++ EDITOR=/bin/nano
++ export PAGER=/usr/bin/less
++ PAGER=/usr/bin/less
++ umask 022
++ unset ROOTPATH
++ for sh in /etc/profile.d/*.sh
++ '[' -r /etc/profile.d/99_bwrap.sh ']'
++ . /etc/profile.d/99_bwrap.sh
+++ chmod 1777 /dev/shm
++ for sh in /etc/profile.d/*.sh
++ '[' -r /etc/profile.d/gawk.sh ']'
++ . /etc/profile.d/gawk.sh
++ unset sh
++ '[' -n '5.0.18(1)-release' ']'
++ '[' -f /etc/bash/bashrc ']'
++ . /etc/bash/bashrc
+++ [[ ehxB != *i* ]]
+++ return
+ echo Europe/Berlin
+ emerge --config sys-libs/timezone-data
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/emerge", line 51, in <module>
    retval = emerge_main()
  File "/usr/lib/python3.7/site-packages/_emerge/main.py", line 1293, in emerge_main
    action=myaction, args=myfiles, opts=myopts)
  File "/usr/lib/python3.7/site-packages/portage/proxy/objectproxy.py", line 30, in __call__
    return result(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/_emerge/actions.py", line 2511, in load_emerge_config
    settings._init_dirs()
  File "/usr/lib/python3.7/site-packages/portage/package/ebuild/config.py", line 1067, in _init_dirs
    ensure_dirs(mydir, gid=gid, mode=mode, mask=modemask)
  File "/usr/lib/python3.7/site-packages/portage/util/__init__.py", line 1407, in ensure_dirs
    perms_modified = apply_permissions(dir_path, **kwargs)
  File "/usr/lib/python3.7/site-packages/portage/util/__init__.py", line 1070, in apply_permissions
    os.chown(filename, uid, gid)
  File "/usr/lib/python3.7/site-packages/portage/__init__.py", line 229, in __call__
    rval = self._func(*wrapped_args, **wrapped_kwargs)
OSError: [Errno 22] Invalid argument: b'/var/lib/portage'
```

I'm not sure why this happens, and I can't replicate it with a VM install from the stage3 downloads. Any ideas? Thanks.

**Comment by toralf** [comment]
Pfffr, assuming the /var/lib/portage exists in the stage3 image, I'd add 
```
emerge --info
```
before
```
emerge --config sys-libs/timezone-data
```
to see if emerge fails there too and why?

**Comment by telans** [comment]
> to see if emerge fails there too and why?

It does, with the same traceback
```
+ emerge --info
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/emerge", line 51, in <module>
    retval = emerge_main()
  File "/usr/lib/python3.7/site-packages/_emerge/main.py", line 1293, in emerge_main
    action=myaction, args=myfiles, opts=myopts)
  File "/usr/lib/python3.7/site-packages/portage/proxy/objectproxy.py", line 30, in __call__
    return result(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/_emerge/actions.py", line 2511, in load_emerge_config
    settings._init_dirs()
  File "/usr/lib/python3.7/site-packages/portage/package/ebuild/config.py", line 1067, in _init_dirs
    ensure_dirs(mydir, gid=gid, mode=mode, mask=modemask)
  File "/usr/lib/python3.7/site-packages/portage/util/__init__.py", line 1407, in ensure_dirs
    perms_modified = apply_permissions(dir_path, **kwargs)
  File "/usr/lib/python3.7/site-packages/portage/util/__init__.py", line 1070, in apply_permissions
    os.chown(filename, uid, gid)
  File "/usr/lib/python3.7/site-packages/portage/__init__.py", line 229, in __call__
    rval = self._func(*wrapped_args, **wrapped_kwargs)
OSError: [Errno 22] Invalid argument: b'/var/lib/portage'
```

The permissions/ownership for that folder on the stage3 is the same as on the actual gentoo install, so I'm a little perplexed.

```
tinderbox@tinderbox ~ $ ls -lah /var/lib/portage/
total 16K
drwxr-sr-x  2 root portage 4.0K Nov 25 00:45 .
drwxr-xr-x 12 root root    4.0K Nov 24 22:53 ..
-rw-rw----  1 root portage   49 Nov 23 14:03 config
-rw-rw----  1 root portage    0 Nov 23 13:51 preserved_libs_registry
-rw-r--r--  1 root portage  239 Nov 25 00:45 world
-rw-r--r--  1 root portage    0 Nov 25 00:45 world_sets
tinderbox@tinderbox ~ $ ls -lah img/17.1_systemd-libressl-20201125-091207/var/lib/portage/
total 12K
drwxr-sr-x 2 root portage 4.0K Nov 23 14:30 .
drwxr-xr-x 9 root root    4.0K Nov 23 14:25 ..
-rw-rw---- 1 root portage   49 Nov 23 14:03 config
-rw-rw---- 1 root portage    0 Nov 23 13:51 preserved_libs_registry
-rw-r--r-- 1 root portage    0 Nov 23 14:30 world
```

---

When chrooting into the system emerge works alright, but not when using bwrap.
bwrap:
```
tinderbox ~ # ls -lah /var/lib/portage/
total 12K
drwxr-sr-x 2 root nobody 4.0K Nov 22 22:22 .
drwxr-xr-x 7 root root   4.0K Nov 22 22:14 ..
-rw-rw---- 1 root nobody   49 Nov 22 22:00 config
-rw-rw---- 1 root nobody    0 Nov 22 21:51 preserved_libs_registry
-rw-r--r-- 1 root nobody    0 Nov 22 22:22 world
```

Should the group be nobody?

---

It seems like it was `--unshare-user-try` causing it. Is that really needed?

**Comment by toralf** [comment]
> It seems like it was `--unshare-user-try` causing it. Is that really needed?

It was an attempt - but it won't worked here. OTOH it doesn't harmed here my hardened Gentoo Linux. If it makes trouble for you then you can safely remove that from bwrap.sh I'd say.
I'll have a look here at that thing too.
